# The workflows key is used to define one or more CI/CD workflows.
workflows:
  android-debug-workflow:
    # A descriptive name for the workflow
    name: Android Gradle APK Build
    
    # Specify the instance type (mac_mini_m2, in this case)
    instance_type: mac_mini_m2
    
    scripts:
      - name: Set up local properties
    
        script: |
          #!/bin/sh
          echo "sdk.dir=$ANDROID_HOME" > "$CM_BUILD_DIR/android/local.properties"
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      
      - name: Grant execute permission to gradlew
        script: |
          chmod +x ./gradlew

      - name: Build Android debug APK
        # The command to run the Gradle build task
        script: |
          ./gradlew assembleDebug

    # Artifacts section specifies which files to save after the build
    artifacts:
      - build/outputs/apk/SA.apk

    publishing:
      # Optional: Configure email publishing
      email:
        recipients:
          - heliojsalles@gmail.com
