workflows:
  android-mac-workflow:
    name: Android Build on macOS
    instance_type: mac_mini_m2
    scripts:
      - name: List Files (Debug)
        script: |
          # Isso vai mostrar no log onde estão seus arquivos
          ls -R
      - name: Run Build
        script: |
          # Procura o gradlew e executa onde quer que ele esteja
          find . -name "gradlew" -exec chmod +x {} \;
          find . -name "gradlew" -exec {} assembleDebug \;
    artifacts:
      - "**/build/outputs/**/*.apk"
