# The name of your workflow, which will be displayed in the Codemagic UI.
workflows:
  android-release:
    name: sa
    # Specify the build machine type.
    instance_type: mac_mini_m2 #

    # Environment variables (optional, for code signing)
    environment:
      vars:
        PACKAGE_NAME: "sa" # Replace with your package name

    # Define the steps for the build process.
steps:
   scripts:
      - name: Clone repository
        script: |
           - git clone https://github.com/heliojsalles-art/smile-clinic-sync.git
           - cd $sa
           - git checkout $sa

      - name: Set up Flutter
        script:
          # This uses the version/channel defined in the "environment" section
          - flutter channel stable
          - flutter upgrade
          - flutter doctor

      - name: Get dependencies
        script:
          - flutter pub get

      # Optional: Add a step for build versioning (e.g., using the built-in build number)
      - name: Set Android build number and version
        script:
          - echo "flutter build name: 1.0.$1.0"
          - echo "flutter build number: $1.0"

      - name: Build Android APK
        script:
          - flutter build apk --release --build-name=1.0.$1.0 --build-number=$1.0 #

artifacts:
  - users\builder\build_outputs\sa.apk #
    
publishing:
  email:
    recipients:
       - heliojsalles@gmail.com
