workflows:
  android-build:
    name: Build Web to APK
    instance_type: mac_mini_m2
    environment:
      node: latest
      java: 21
    scripts:
      - name: Install dependencies and build web
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npm run build
      - name: Capacitor Sync
        script: |
          [ ! -f "capacitor.config.json" ] && npx cap init "My App" "com.example.app" --web-dir dist
          npx cap add android || true
          npx cap sync android
            - name: Generate App Icons
      - name: Icon
         script: |
          # Use the correct scoped package name
          npm install -g @capacitor/assets
          
          # Ensure your icon exists at this path in your repo
          # If your icon is in a different folder, change 'assets/icon.png' below
          npx @capacitor/assets generate --android --icon assets/icon.png
      - name: Build APK with Gradle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
