workflows:
  grabber-android-build:
    name: Grabber Android Build
    instance_type: mac_mini_m2 # Use a macOS instance type

    scripts:
      - name: Set up environment and build with Grabber
        script: |
          cd \users\builder\programs\gradle-8.14.1\bin\
          grabber build android sa.apk
          
          # You may need to copy the generated APK to a standard artifacts directory
          # for Codemagic to find it easily. Check your specific Grabber output path.
          # Example:
          cp sa.apk $CM_ARTIFACT_DIR/sa.apk

    artifacts:
      # Specifies the path where the resulting APK artifacts are located.
      - app/build/outputs/sa.apk # Adjust path based on your project structure

   
    publishing:
      # Optional: Configure email publishing
      email:
        recipients:
          - heliojsalles@gmail.com
