# The name of the workflow, displayed in the Codemagic UI
workflows:
  android-release:
    name: Android Release Build
    # Use a macOS instance for the build
    instance_type: mac_mini_m2

    environment:
      # Define the Flutter version to use (e.g., stable, beta, 3.7.6)
      flutter: stable
      # Define environment variables, including code signing secrets (if used)
      
    scripts:
      # Clone the repository
      - name: Get source codes
        script: |
          git clone <https://github.com/heliojsalles-art/smile-clinic-sync/archive/refs/tags/Dental.zip> .
      
      # Set up Flutter environment
      - name: Set up Flutter
        script: |
          flutter channel $FLUTTER_VERSION
          flutter upgrade
      
      # Get Flutter dependencies
      - name: Get dependencies
        script: |
          flutter pub get

      # Optional: Add script for build versioning (e.g., using Codemagic CLI tools)
      # - name: Increment build number
      #   script: |
      #     # Example using Codemagic's built-in tools for versioning
      #     # Check Codemagic documentation for specifics
      #     # latest_build_number=$(app-store-connect get-latest-build-number --bundle-id "<your_bundle_id>")
      #     # new_build_number=$(($latest_build_number + 1))
      #     # flutter build apk --build-number=$new_build_number
      
      # Build the Android APK in release mode
      - name: Build Android APK
        script: |
          flutter build apk --release

    artifacts:
      # Define the paths to the build artifacts to be saved by Codemagic
      - build/app/outputs/flutter-apk/SA.apk

    publishing:
      # Optional: Configure email publishing
      email:
        recipients:
          - heliojsalles@gmail.com
