# A basic Codemagic.yaml for a Flutter project to build an Android APK on macOS.
# For more examples and advanced configurations, check the official [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects) repository.

workflows:
  android-release-workflow:
    name: Android Release Workflow (macOS)
    # Specify a macOS instance type for the build machine
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      # Specify the Flutter version
      flutter: stable
      # Add environment variables for code signing if needed (set in Codemagic UI)
      # groups:
      #   - android-signing-credentials
    
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get

      # Optional: Add a script for automatic versioning (e.g., --build-number=$PROJECT_BUILD_NUMBER)
      # - name: Increment build number
      #   script: |
      #     flutter build apk --release --build-number=$PROJECT_BUILD_NUMBER

      - name: Build Android Release APK
        script: flutter build apk --release

    artifacts:
      # Define which files to save as build artifacts
      - builder/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - Users/builder/programs/build_outputs/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    
    # Optional: Add publishing section (e.g., to email, Google Play, Firebase)
    # publishing:
    #   email:
    #     recipients:
    #       - name@gmail.com
