workflows:
  android-build:
    name: Build Web to APK
    instance_type: mac_mini_m2
    environment:
      node: latest
      java: 21
    scripts:
      - name: Install dependencies and build web
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npm run build
      - name: Capacitor Sync
        script: |
          if [ ! -f "capacitor.config.json" ]; then
            npx cap init "Salles Atelie" "com.example.app" --web-dir dist
            npx cap add android
          fi
          npx cap sync android
      - name: Generate App Icons
        script: |
          npm install -g @capacitor/assets
          ICON_PATH=$(find . -name "icon.png" -not -path "*/node_modules/*" | head -n 1)
          if [ -n "$ICON_PATH" ]; then
            echo "Ícone encontrado em: $ICON_PATH"
            mkdir -p assets
            cp "$ICON_PATH" assets/icon.png
            npx @capacitor/assets generate --android
          else
            echo "ERRO: Arquivo icon.png não encontrado."
            exit 1
          fi
      - name: Build APK with Gradle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
