workflows:
  android-release:
    name: sa
    instance_type: mac_mini_m2 
    # Use '.' para a raiz do projeto onde está o pubspec.yaml
    working_directory: Users/builder/programs/flutter
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "sa"
    scripts:
      - name: Android build
        script: |
          flutter build apk --release --build-name=1.0.0 --build-number=${BUILD_NUMBER:-1} 
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - heliojsalles@gmail.com
