workflows:
  android-build:
    name: Build Web to APK
    instance_type: mac_mini_m2
    environment:
      node: latest
    scripts:
      - name: Install dependencies and build web
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npm run build
      - name: Capacitor Sync
        script: |
          # Inicializa se necessário, mas garante a atualização dos arquivos web no Android
          [ ! -f "capacitor.config.json" ] && npx cap init "My App" "com.example.app" --web-dir dist
          npx cap add android || true
          npx cap sync android
      - name: Build APK with Gradle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
