workflows:
  android-release:
    name: sa
    instance_type: mac_mini_m2 
    # Mantenha '.' se o pubspec.yaml estiver na raiz. 
    # Se estiver em uma pasta, use apenas o nome dela (ex: 'app_folder')
    working_directory: . 
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "sa"

    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: List files to find pubspec
        script: |
          echo "Diretório atual: $(pwd)"
          find . -maxdepth 2 -name "pubspec.yaml"
      - name: Get dependencies
        script: |
          # Se o pubspec estiver em uma subpasta, entre nela primeiro
          # cd nome_da_sua_pasta 
          flutter pub get
      - name: Build Android APK
        script: |
          # O build number precisa do prefixo $ para ser lido como variável
          flutter build apk --release --build-name=sa --build-number=${BUILD_NUMBER:-1}

    artifacts:
      # O Codemagic busca a partir da pasta do projeto definida acima
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - heliojsalles@gmail.com
