# The name of the workflow
workflows:
  android-mac-workflow:
    name: Android Build on macOS
    # Specify the macOS instance type
    instance_type: mac_mini_m2

    # Environment variables (optional, e.g., if you have sensitive credentials in a group)
    # environment:
    #   groups:
    #     - android_credentials

    # Define the scripts to run
    scripts:
      - name: Set up Android SDK
        script: |
          # The Android SDK is pre-installed on Codemagic machines
          # Ensure appropriate permissions or setup if custom SDK path is used
          echo "Android SDK is ready to use."

      - name: Run Gradle assembleDebug
        script: |
          # Use the gradlew wrapper to build the debug APK
          ./gradlew assembleDebug

    # Define where the artifacts (APK file) can be found
    artifacts:
      - build/outputs/**/**/*.apk
    
    # Optional: Configure automatic build triggering
    # triggering:
    #   branch_patterns:
    #     - pattern: master
    #       include: true
    #       trigger_test: true
    #     - pattern: develop
    #       include: true
    #       trigger_test: true
