workflows:
  android-build:
    name: Build Web to APK
    instance_type: mac_mini_m2
    environment:
      node: latest
      java: 21
    scripts:
      - name: Install dependencies and build web
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npm run build
      - name: Capacitor Sync
        script: |
          # Inicializa se o config não existir, caso contrário apenas sincroniza
          if [ ! -f "capacitor.config.json" ]; then
            npx cap init "My App" "com.example.app" --web-dir dist
            npx cap add android
          fi
          npx cap sync android
      - name: Generate App Icons
        script: |
          # Instala a ferramenta de assets
          npm install -g @capacitor/assets
          
          # Verifica se o ícone existe antes de tentar gerar (evita erro silencioso)
          if [ -f "assets/icon.png" ]; then
            npx @capacitor/assets generate --android --icon assets/icon.png
          else
            echo "Erro: assets/icon.png não encontrado no diretório $(pwd)"
            exit 1
          fi
      - name: Build APK with Gradle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
