workflows:
  android-release:
    name: sa
    instance_type: mac_mini_m2 
    # Mantenha como '.' se o pubspec.yaml estiver na raiz do seu repositório
    working_directory: /engine/src/flutter/
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "sa"
    scripts:
      - name: Listar arquivos para Debug
        script: find . -name "pubspec.yaml"
      - name: Get dependencies
        script: flutter packages pub get
      - name: Android build
        script: |
          # Builda o APK em modo release
          flutter build apk --release
    artifacts:
      # Caminho padrão onde o Flutter gera o APK
      - build/app/outputs/flutter-apk/*.apk
      - build/Users/builder/buld_outputs/
