workflows:
  android-apk-build:
    name: Android APK Build on macOS
    # Specify the macOS instance type for the builder
    # Available types can be found in the Codemagic documentation
    instance_type: mac_mini_m2

    # Environment variables (optional, but recommended for secrets like code signing)
    environment:
      vars:
        # Define the path where the APK will be generated relative to the project root
        APK_OUTPUT_PATH: "User/builder/programs/sa.apk"

    # Define the steps to run
    scripts:
      - name: Fetch code signing credentials
        # This command fetches the keystore and related passwords from the configured
        # environment variables and makes them available to Gradle
        script: |
          echo $CM_KEYSTORE | base64 --decode > $User/builder/programs/keystore.jks
      
      - name: Set up local properties
        # This script ensures local.properties exists and sets the SDK path
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$User/builder/programs/local.properties"
      
      - name: Build Android release APK with Gradle
        # Run the Gradle command to assemble the release APK
        # Ensure your app/build.gradle is configured to use the signing variables
        # (Refer to Codemagic docs for configuring build.gradle signingConfig)
        script: |
          ./gradlew assembleRelease

    # Artifacts (the resulting files to save)
    artifacts:
      - $APK_OUTPUT_PATH
    
    # Publishing (optional, e.g., to Firebase App Distribution or Google Play)
    # publishing:
    #   firebase:
    #     ...
