workflows:
  android-release:
    name: sa
    instance_type: mac_mini_m2 
    max_build_duration: 60
    environment:
      flutter: stable # Define a versão do Flutter
      vars:
        PACKAGE_NAME: "sa"

    scripts:
      # O Codemagic já clona seu repo automaticamente na pasta $CM_BUILD_DIR
      - name: Get dependencies
        script: |
          flutter packages pub get
      
      - name: Build Android APK
        script: |
          # O comando 'build apk' gera o arquivo em build/app/outputs/flutter-apk/
          flutter build apk --release --build-name=sa --build-number=$1.0

    artifacts:
      # Caminho padrão onde o Flutter despeja o APK no macOS/Linux
      - Users/builder/build_outputs/
    
    publishing:
      email:
        recipients:
          - heliojsalles@gmail.com
