workflows:
  android-build:
    name: Build Web to APK (Java 17)
    instance_type: mac_mini_m2
    scripts:
      - name: Set up Java 17
        script: |
          # Define o Java 17 como padrão
          sdk use java 17.0.10-tem
          java -version

      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npm run build

      - name: Sync Capacitor & Downgrade Java Config
        script: |
          if [ ! -f "capacitor.config.json" ]; then
            npx cap init "My App" "com.example.app" --web-dir dist
          fi
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          npx cap copy android
          
          # COMANDO CRUCIAL: Altera o build.gradle para usar Java 17 em vez de 21
          find android -name "build.gradle" -exec sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' {} +

      - name: Build APK with Gradle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
