workflows:
  android-build-workflow:
    name: Android Build Workflow
    # Specify the instance type (macOS in this case)
    instance_type: mac_mini_m2 
    max_build_duration: 60
    
    environment:
      # Optional: set up Java version if needed, default is fine for most cases
      # java: "17" 
      # Environment variables for code signing (defined in Codemagic UI)
      groups:
        # Replace 'android-signing-credentials' with your actual environment variable group name in Codemagic
        - android-signing-credentials 

    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$HOME/programs/android-sdk" > "$CM_BUILD_DIR/local.properties"
      
      - name: Clean build
        script: ./gradlew built
        
      - name: Build debug APK
        # Use a signing config that uses the uploaded keystore for release builds
        script: ./gradlew assembleRelease

    artifacts:
      # Define which files to export as build artifacts
      - build/SA.apk

    publishing:
      # Optional: Configure email publishing
      email:
        recipients:
          - heliojsalles@gmail.com
