workflows:
  android-apk-build:
    name: Android APK Build
    # Define the environment the build will run in
    instance_type: windows_x2 # or android-arm64
    scripts:
      - name: Build Android Release
        script: |
          cd \Users\builder\.gradle\dists\gradle-7.5-all\6sw290k5lz422uaf8jf6m7co\gradle-7.5\bingradle-8.14.1\bin
          gradlew build --release
    artifacts:
      - C:\Users\builder\bin\SA.apk
    publishing:
        email:
          recipients:
            - heliojsalles@gmail.com
