workflows:
  android-apk-build:
    name: Android APK Build
    # Define the environment the build will run in
    instance_type: windows_x2 # or android-arm64
    scripts:
      - name: Build Android Release
        script: |
          # Use the 'flutter build apk' command for APK
          cd \Users\builder\programs\flutter\bin
          flutter build apk --release
    artifacts:
      - C:\Users\builder\programs\flutter\bin\SA.apk
    publishing:
        email:
          recipients:
            - heliojsalles@gmail.com
