workflows:
  android-release:
    name: Android Release Workflow
    instance_type: windows_x2 # Specifies the Windows build machine

    environment:
      # Environment variables for code signing and Google Play publishing are handled via variable groups.
      # You must define these in the Codemagic UI and assign them to groups (e.g., android_credentials, google_play).
    vars:
      
        # Define the build mode (release for APK/AAB for publishing)
        BUILD_MODE: release

    scripts:
      # Clone the repository
      - name: Clone repository
        script: git clone --depth 1 $CM_REPO_URL $CM_BUILD_DIR

      # Select the desired Flutter version
      - name: Set up Flutter version
        script: flutter channel $FLUTTER_CHANNEL && flutter upgrade

      # Get project dependencies
      - name: Get dependencies
        script: flutter pub get

      # Build the Android APK (or AAB)
      - name: Build Android Release
        script: |
          # Use the 'flutter build apk' command for APK
          flutter build apk --release

    artifacts:
      # Archive the generated APK file
      - build/app/outputs/flutter-apk/smartagenda.apk
      # Optionally, archive the AAB file if needed
      # - build/app/outputs/bundle/release/*.aab

    publishing:
      
