workflows:
  android-release:
    name: sa
    instance_type: mac_mini_m2 
    # ADICIONE O NOME DA PASTA ONDE ESTÁ O SEU PUBSPEC.YAML
    working_directory: Users/builder/programs/flutter_3_38_5/bin
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "sa"

    scripts:
    
      - name: Get dependencies
        script: |
          # Tenta limpar o cache antes de baixar
          flutter pub cache repair 
          flutter packages pub get

      
      - name: Build Android APK
        script: |
          # O Codemagic injeta o BUILD_NUMBER automaticamente se configurado
          flutter build apk --release --build-name=sa --build-number=${BUILD_NUMBER:-1}

    artifacts:
      # Use caminhos relativos ao working_directory ou glob patterns
      - Users/builder/programs/flutter_3_38_5/bin/sa.apk
      - Users/builder/build_outputs/sa.apk
    publishing:
      email:
        recipients:
          - heliojsalles@gmail.com
