# The name of the workflow is displayed in the Codemagic UI
workflows:
  android-apk-build:
    name: Android APK Build
    # Define the environment the build will run in
    instance_type: windows_x2 # or android-arm64
    
    # Define environment variables if needed (e.g., for secrets)
    environment:
      vars:
        # Example variable, add others in the Codemagic UI as secrets
        PACKAGE_NAME: "io.codemagic.androidquicksample"

    # Define steps to run before the build
    scripts:
      # Set the Android SDK location, required by Gradle
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      # Build the Android APK
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug # Use assembleRelease for a release build

    # Specify which files should be available as build artifacts
    artifacts:
      - build/app/outputs/apk/release/app-release.apk
    publishing:
     email:
    recipients:
      - heliojsalles@gmail.com
