# The name of your workflow, which will be displayed in the Codemagic UI.
workflows:
  android-release:
    name: sa
    # Specify the build machine type.
    instance_type: mac_mini_m2 #

    # Environment variables (optional, for code signing)
    environment:
      vars:
        PACKAGE_NAME: "sa" # Replace with your package name

    # Define the steps for the build process.
steps:
   scripts:
      - name: Clone repository
        script: |
           - git clone https://github.com/heliojsalles-art/smile-clinic-sync.git $sa
           - cd $sa
           - git checkout $sa

      - name: Get dependencies
        script:
          - flutter pub get

      - name: Build Android APK
        script:
          - flutter build apk --release

artifacts:
  - users\builder\build_outputs\sa.apk #
    
publishing:
  email:
    recipients:
       - heliojsalles@gmail.com
