workflows:
  android-build:
    name: Build Web to APK
    instance_type: mac_mini_m2
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npm run build # Gera a pasta 'dist'

      - name: Add Android Platform
        script: |
          # Inicializa o Capacitor se não houver config
          [ ! -f "capacitor.config.json" ] && npx cap init "My App" "com.example.app" --web-dir dist
          npx cap add android
          npx cap copy android

      - name: Build APK with Gradle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
