workflows:
  android-release:
    name: sa
    instance_type: mac_mini_m2 
    # Use '.' para a raiz do projeto onde está o pubspec.yaml
    working_directory: /Users/builder/programs/flotter/bin
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "sa"
    scripts:
      - name: Anfoid build
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - heliojsalles@gmail.com
