workflows:
  # This is the unique ID for your workflow
  android-apk-build:
    # A human-readable name for the workflow
    name: Android APK Build
    # Specifies the type of virtual machine to use for the build
    instance_type: mac_mini_m2
    # The maximum duration the build can run (in minutes)
    max_build_duration: 60

    # Environment variables can be defined here or sourced from variable groups in the UI
    environment:
      # Use a specific Flutter version (e.g., stable, beta, or specific version number)
      flutter: stable
      # Add a variable group if you are using code signing or publishing credentials
      # groups:
      #   - android_credentials_group # Name of the variable group in Codemagic UI

    # Define the sequence of actions for the build
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      
      - name: Set up local properties (optional, mainly for native Android projects)
        script: |
          # This line ensures the flutter SDK path is set in android/local.properties
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Build Android debug APK
        script: flutter build apk --debug

      # For a release build, you would use:
      # - name: Build Android release APK
      #   script: flutter build apk --release

    # Define which files from the build machine should be saved as build artifacts
    artifacts:
      - build/outputs/smartagenda.apk
    publishing:
        email:
          recipients:
            - heliojsalles@gmail.com
