workflows:
  android-workflow:
    name: Android APK Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - name: Set up local properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Android APK
        script: | 
           # 1. Entra na pasta onde o gradle realmente está
          cd /android 
          
          # 2. Cria o arquivo de configuração do SDK lá dentro
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          
          # 3. Dá permissão e roda o build
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
