workflows:
  android-mac-workflow:
    name: Android Build on macOS
    instance_type: mac_mini_m2
    scripts:
      - name: Prepare Gradlew Permissions
        script: |
          # Garante que o script tenha permissão de execução no macOS
          chmod +x gradlew || chmod +x android/gradlew 

      - name: Build Android APK
        script: |
          # Se o seu projeto Android estiver em uma subpasta (comum em Flutter/React Native), 
          # use 'cd android && ./gradlew assembleDebug'. 
          # Caso contrário, use apenas './gradlew assembleDebug'.
          ./gradlew assembleDebug || (cd android && ./gradlew assembleDebug)

    artifacts:
      - build/outputs/**/**/*.apk
      - android/app/build/outputs/**/**/*.apk
